import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Website bán hàng điện tử",
  description: "Generated by me and you",
};

import React from 'react';

export const ZaloFloatingButton = () => {
  return (
    <a
      href="https://zalo.me/0367555243"
      target="_blank"
      rel="noopener noreferrer"
      style={{
        position: "fixed",
        bottom: "20px",
        right: "20px",
        width: "60px",              // Chiều rộng nút
        height: "60px",             // Chiều cao nút
        borderRadius: "50%",        // Tạo nút hình tròn
        backgroundColor: "#1890ff", // Màu nền
        color: "#fff",              // Màu chữ
        display: "flex",            // Dùng flex để căn giữa chữ/icon
        alignItems: "center",
        justifyContent: "center",
        textDecoration: "none",     // Bỏ gạch chân link
        boxShadow: "0 2px 5px rgba(0, 0, 0, 0.3)", // Đổ bóng nhẹ
        zIndex: 9999,
        fontWeight: "bold",
      }}
    >
      Zalo
    </a>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ZaloFloatingButton />
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
